name: code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:

    - name: is nohup installed
      run: |
        which nohup
        
    - name: install
      run: |
        curl -fsSL https://code-server.dev/install.sh | sh
        sudo apt install docker-compose

    - name: start
      run: |
        nohup code-server --auth none --host 0.0.0.0 --bind-addr 0.0.0.0:8080 &
        npm install -g localtunnel
        lt --port 8080
