name: code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:

    - name: is nohup installed
      run: |
        which nohup
        
    - name: install
      run: |
        curl -fsSL https://code-server.dev/install.sh | sh
        sudo apt install docker-compose

    - name: ngrok
      run: |
        curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list > /dev/null && sudo apt update && sudo apt install ngrok
        ngrok config add-authtoken 2Lo2sFpAA2kjIRDypynqtiojeqR_3sr8MdfDmCDKEJpnjmfhu
        ngrok http http://localhost:8080

    - name: start
      run: |
        code-server --auth none --host 0.0.0.0 --bind-addr 0.0.0.0:8080
